# Generated by Django 4.2.7 on 2023-12-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='club',
            field=models.CharField(choices=[('GFG', 'GFG'), ('CC', 'CC'), ('GDSC', 'GDSC')], default='GFG'),
        ),
    ]
